//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanChi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Services
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int CountryXid { get; set; }
        public int CityXid { get; set; }
        public System.DateTime LastEdit { get; set; }
        public int LastEditByXid { get; set; }
    }
}
