//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanChi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Vehicle
    {
        public int Id { get; set; }
        public string VehicleName { get; set; }
        public string VIN { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<int> VehicleYear { get; set; }
        public Nullable<int> VehicleMakeId { get; set; }
        public Nullable<int> VehicleModelId { get; set; }
        public string Trim { get; set; }
        public string RegistrationState { get; set; }
        public string Color { get; set; }
        public Nullable<int> VehicleBodyTypeId { get; set; }
        public Nullable<int> VehicleFuelTypeID { get; set; }
        public Nullable<double> FuelQuality { get; set; }
        public Nullable<double> FuelTank1Capacity { get; set; }
        public Nullable<double> FuelTank2Capacity { get; set; }
        public Nullable<double> OilCapacity { get; set; }
        public Nullable<double> FileName { get; set; }
    }
}
