//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanChi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuRole
    {
        public System.Guid Id { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid MenuId { get; set; }
        public string UserName { get; set; }
        public string URL { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public byte ActiveFag { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Role Role { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
