//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanChi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_RequestVehicle
    {
        public int Id { get; set; }
        public Nullable<int> QuoteRequestXid { get; set; }
        public Nullable<int> ServicesXid { get; set; }
        public Nullable<int> VehicelXid { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Status { get; set; }
    }
}
