//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanChi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesContractRate
    {
        public int Id { get; set; }
        public Nullable<int> ServicesContractId { get; set; }
        public Nullable<int> VehicleXid { get; set; }
        public Nullable<decimal> SellRate { get; set; }
        public Nullable<decimal> BuyRate { get; set; }
        public System.DateTime LastEdit { get; set; }
        public int LastEditByXid { get; set; }
    }
}
