//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanChi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesContractDate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ServicesContractId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
        public string LastEditByXid { get; set; }
        public string Comments { get; set; }
    }
}
