//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanChi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public System.Guid LogId { get; set; }
        public string Module { get; set; }
        public string UserId { get; set; }
        public Nullable<int> UserFunction { get; set; }
        public Nullable<int> EventResult { get; set; }
        public Nullable<System.DateTime> FuncDateTime { get; set; }
        public string Source { get; set; }
        public string Transdata { get; set; }
        public string WSName { get; set; }
    }
}
