//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanChi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.MenuRoles = new HashSet<MenuRole>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public string UserName { get; set; }
        public string UserCode { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public byte[] Picture { get; set; }
        public string Address { get; set; }
        public string HomePhone { get; set; }
        public string Ext { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.Guid> LanguageID { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> FirstWorkingDate { get; set; }
        public string UserHRIS { get; set; }
        public string Diploma { get; set; }
        public string Position { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuRole> MenuRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
